### ISSUE TITLE
docker 25: MANIFEST_BLOB_UNKNOWN: blob unknown to registry

### ISSUE THREAD

**Issue by coopstah13** [mesosphere/mindthegap#655] opened 2024-03-22 12:49 UTC
I'm using `create image-bundle` command and getting this error:

```
 ✓ Parsing image bundle config
 ✓ Creating temporary directory
 ✓ Starting temporary Docker registry
 ✗ Pulling requested images [                                    0/13] (time elapsed 09s) 
PUT http://127.0.0.1:33571/v2/XXX/manifests/sha256:9a4a8f7234957bc76c3a8b062070e429a1b8a23c36c24e5d6a26e9b1d91bc410: multiple errors returned:
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:064b40dd2dfb098da5b4d43876da5d481047121e1ed560129383b74d30b5fe99;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:6626c9b5b2de04d53cccd1235e03fcb18f812284b61ce453859d282ce8d19cd0;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:7b92e5eddc133237670f4c75659800f8bd0c3384a713318c79d0531f91b696f2;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:5ace0b795b80b845f07ef9bb3cc42b3fcab0ec334dd92b68c7d9d710c5986ed4;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:0ca3d0f7e3e1281d6a3d1ce1a872b6f0761d70842e6e57a02ba6806e9f5557e6;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:b70bbbe162477aeb68d5c19a3d7d4da389c537b04d11eeabbe35b651314b8a89;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:b5f71c00b65306805e43337cc17e101eaf23e050afe4f3a0c6647f87f48f6fe6;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:b5f71c00b65306805e43337cc17e101eaf23e050afe4f3a0c6647f87f48f6fe6;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:20bfa07587c5c05b57c64bce2a61ca831ae4641161f5c717ceb233579847a76b;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:255c33047a850954ffbd0de23449674d8dce49b748e2af90afd1b8a1f1824a0a;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:fb97d22de48e2b66fbc1a59d651f7cb9e169c9f4a2008320a78012b3fe31f7b4;
MANIFEST_BLOB_UNKNOWN: blob unknown to registry; sha256:ee1d465b6ef5a03fccc178453de8d3b619fbe53635fb9e7c9f8893b98c5e0af9
```

mindthegap version: v1.13.0
OS: ubuntu 22.04
Docker:
```
Client: Docker Engine - Community
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        5dc9bcc
 Built:             Tue Mar 19 15:05:10 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       e63daec
  Built:            Tue Mar 19 15:05:10 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Downgraded my docker to this and it worked:
```
Client: Docker Engine - Community
 Version:           24.0.9
 API version:       1.43
 Go version:        go1.20.13
 Git commit:        2936816
 Built:             Thu Feb  1 00:48:39 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.9
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.13
  Git commit:       fca702d
  Built:            Thu Feb  1 00:48:39 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jimmidyson** [comment] 2024-03-26 11:52
Thanks for the report! I'm a bit confused why the Docker version matters because under the hood we don't use a container runtime at all 🤔 

Could you share an example images config file so I can try to reproduce?

**Comment by coopstah13** [comment] 2024-03-26 18:18
hello, thanks for asking, but I am assuming the project is subject to this issue here: https://github.com/google/go-containerregistry/issues/1870

**Comment by coopstah13** [comment] 2024-03-26 18:24
i think this problem will go away for me, if you make a new release using v0.19 or later of that library

**Comment by jimmidyson** [comment] 2024-03-26 19:35
Aha thank you again! I'll get that fixed asap

**Comment by jimmidyson** [comment] 2024-03-26 19:52
Released v1.13.1! Please can you try it out?

**Comment by jimmidyson** [comment] 2024-03-27 09:14
Fixed in v1.13.1 - closing. Please reopen if this is still causing you issues.

**Closed by jimmidyson** 2024-03-27 09:14 UTC

**Comment by coopstah13** [comment] 2024-03-27 12:16
confirmed fix after I updated to docker 26, thanks!

**Comment by jimmidyson** [comment] 2024-03-27 15:25
Nice! Thanks for confirming @coopstah13 !
